# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requestApp', '0002_auto_20170712_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='idnum',
        ),
        migrations.RemoveField(
            model_name='user',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reason',
        ),
    ]
