# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestApp', '0005_auto_20170712_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='idnum',
            new_name='UCard_ID',
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
