# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requestApp', '0007_user_man_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='COLOUser',
        ),
    ]
