# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestApp', '0008_auto_20170713_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='colouser',
            name='man_approved',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='colouser',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
