# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestApp', '0009_auto_20170713_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='colouser',
            name='COLO_approved',
            field=models.BooleanField(default='False'),
        ),
    ]
