# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestApp', '0010_colouser_colo_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colouser',
            name='COLO_approved',
            field=models.BooleanField(default='False', verbose_name='COLO Manager Approved'),
        ),
        migrations.AlterField(
            model_name='colouser',
            name='UCard_ID',
            field=models.PositiveIntegerField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='colouser',
            name='email',
            field=models.EmailField(default='', max_length=100, verbose_name='Employee Email'),
        ),
        migrations.AlterField(
            model_name='colouser',
            name='man_approved',
            field=models.BooleanField(default='False', verbose_name='Manager Approval'),
        ),
        migrations.AlterField(
            model_name='colouser',
            name='man_email',
            field=models.EmailField(default='', max_length=100, verbose_name='Manager Email'),
        ),
        migrations.AlterField(
            model_name='colouser',
            name='manager',
            field=models.CharField(default='', max_length=100, verbose_name='Manager Name'),
        ),
        migrations.AlterField(
            model_name='colouser',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Employee Name'),
        ),
        migrations.AlterField(
            model_name='colouser',
            name='phone',
            field=models.PositiveIntegerField(default='', verbose_name='Employee Phone Number'),
        ),
        migrations.AlterField(
            model_name='colouser',
            name='reason',
            field=models.CharField(default='', max_length=100, verbose_name='Reason for request'),
        ),
        migrations.AlterField(
            model_name='colouser',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='Time Of Submission'),
        ),
    ]
