# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestApp', '0011_auto_20170713_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colouser',
            name='man_approved',
            field=models.BooleanField(default='False', error_messages={'required': 'Must accept'}, verbose_name='Manager Approval'),
        ),
    ]
