# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('requestApp', '0013_auto_20170713_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='colouser',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
