# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requestApp', '0016_auto_20170713_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colouser',
            name='unique_id',
        ),
    ]
