# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestApp', '0017_remove_colouser_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colouser',
            name='email',
            field=models.EmailField(default='', max_length=50, verbose_name='Employee Email'),
        ),
        migrations.AlterField(
            model_name='colouser',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Employee Name'),
        ),
        migrations.AlterField(
            model_name='colouser',
            name='reason',
            field=models.CharField(default='', max_length=50, verbose_name='Reason for request'),
        ),
    ]
