# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestApp', '0019_auto_20170713_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='COLOManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
