# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('requestApp', '0020_colomanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='COLOManager',
        ),
        migrations.AddField(
            model_name='colouser',
            name='tracker',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
