# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('requestApp', '0022_auto_20170718_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colouser',
            name='id',
        ),
        migrations.AddField(
            model_name='colouser',
            name='dep',
            field=models.CharField(choices=[('UMass Student', 'UMass Student'), ("President's Office", "President's Office"), ('Other', 'Other')], default='', max_length=1, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='colouser',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='Employee Email'),
        ),
        migrations.AlterField(
            model_name='colouser',
            name='man_email',
            field=models.EmailField(max_length=25, verbose_name='Manager Email'),
        ),
        migrations.AlterField(
            model_name='colouser',
            name='manager',
            field=models.CharField(max_length=100, verbose_name='Manager Name'),
        ),
        migrations.AlterField(
            model_name='colouser',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Employee Name'),
        ),
        migrations.AlterField(
            model_name='colouser',
            name='phone',
            field=models.PositiveIntegerField(verbose_name='Employee Phone Number'),
        ),
        migrations.AlterField(
            model_name='colouser',
            name='reason',
            field=models.CharField(max_length=50, verbose_name='Reason for Request'),
        ),
        migrations.AlterField(
            model_name='colouser',
            name='tracker',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
