# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requestApp', '0024_auto_20170719_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colouser',
            name='user',
        ),
    ]
