# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('requestApp', '0025_remove_colouser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colouser',
            name='tracker',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
