# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestApp', '0026_auto_20170719_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colouser',
            name='UCard_ID',
            field=models.PositiveIntegerField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='colouser',
            name='dep',
            field=models.CharField(choices=[('UMass Student', 'UMass Student'), ("President's Office", "President's Office"), ('Other', 'Other')], default='', max_length=20, verbose_name='Department'),
        ),
    ]
