# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestApp', '0031_auto_20170725_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colouser',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='Timestamp'),
        ),
    ]
