# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestApp', '0034_auto_20170726_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colouser',
            name='email',
            field=models.EmailField(max_length=25, verbose_name='Employee Email'),
        ),
        migrations.AlterField(
            model_name='colouser',
            name='manager',
            field=models.CharField(max_length=25, verbose_name='Manager Name'),
        ),
    ]
