# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestApp', '0037_auto_20170802_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colouser',
            name='dep',
            field=models.CharField(choices=[('UMass Student', 'UMass Student'), ('UMass Staff', 'UMass Staff'), ("President's Office", "President's Office"), ('Medical School', 'Medical School'), ('Other', 'Other')], default='', max_length=20, verbose_name='Department'),
        ),
    ]
