# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestApp', '0038_auto_20170816_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colouser',
            name='phone',
            field=models.CharField(max_length=14, verbose_name='Employee Phone Number'),
        ),
    ]
