# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestApp', '0039_auto_20170816_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colouser',
            name='dep',
            field=models.CharField(choices=[('UMass Amherst', 'UMass Amherst'), ('UMass Boston', 'UMass Boston'), ("UMass President's Office", " UMass President's Office"), ('UMass Medical School', 'UMass Medical School'), ('Other', 'Other')], default='', max_length=20, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='colouser',
            name='phone',
            field=models.PositiveIntegerField(verbose_name='Employee Phone Number'),
        ),
    ]
