# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestApp', '0043_auto_20170816_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colouser',
            name='reason',
            field=models.CharField(choices=[('COLO Area Access', 'COLO Area Access'), ('LSLDC Card Access', 'LSLDC Card Access')], default='', max_length=20, verbose_name='Reason for request'),
        ),
    ]
